### ISSUE TITLE
Command arguments don't support glob patterns

### ISSUE THREAD

**Issue by SalsaGal** [TheOnlyMrCat/runscript#1]
I have a line which takes `src/*.cpp` as an argument, but I get the error `clang: error: no such file or directory: 'src/*.cpp'`. It's referring to the right directory because if I use a single file as the argument it picks up the file (but obviously all its includes are missing).

**Comment by TheOnlyMrCat** [comment]
Working on that now. Will appear in 1.1.0

**Comment by TheOnlyMrCat** [comment]
I have made an effort to put glob-matching in, however, the library I am using does not support proper globs. It supports minimal use-cases, such as the case described in this issue, though, and I won't be putting much effort into increasing this support unless someone actually wants it.
